[tool.poetry]
name = "foobar"
version = "0.1.0"
description = ""
authors = ["selimslab <hselimozturk@gmail.com>"]

[tool.poetry.dependencies]
python = "2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
