#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: home

# Short bio or description (displayed in the header)
description: bicycle for the mind 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/120px-The_Great_Wave_off_Kanagawa.jpg

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-WT9QGKVX1Q

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://selimslab.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/


# The release of Jekyll Now that you're using
version: v1.2.0

markdown: kramdown
highlighter: rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
    block:
      line_numbers: true
      
# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

theme: 

collections_dir: HOME

collections:
  arts:    
    output: true 
    permalink:  /:title/

  atoms:    
    output: true 
    permalink:  /:title/

  engineering:    
    output: true 
    permalink:  /:title/

  philosophy:    
    output: true 
    permalink:  /:title/

  practical-skills:    
    output: true 
    permalink:  /:title/

  science:    
    output: true 
    permalink:  /:title/

  social-sciences:    
    output: true 
    permalink:  /:title/

  math:    
    output: true 
    permalink:  /:title/

  technology:    
    output: true 
    permalink:  /:title/



defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: post