[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.11.10",
    "youtube-transcript-api>=1.1.0",
    "yt-dlp>=2025.4.30",
]
